### PR TITLE
Fixed small issues with GML parsing

### PR DESCRIPTION
**Pull request by pksorensen**
I had some small issues with parsing some GML that I now fixed in the lib.

Also some issue with coordinate swapping, and using the same conclussion as given here: http://www.gdal.org/drv_gml.html

i also swapped the gml coordinates when reading.

### CODE REVIEW

**Comment by emmanuelmathot** [comment]
Thank you for the correction for the gml parsing. On the other hand, the tests are failing with the changes about the corrdinates swapping. I am not sure to understand why the coordinates should be swapped in a gmlPosList. I follow the gml reference.

**Comment by s093294** [comment]
According to GDAl reference, if an element provides srsName attribute, like:

<Surface srsName="urn:ogc:def:crs:OGC:1.3:CRS84" ..>

then its longitude,latitude instead of latitude,longitude. 

Its not needed to verify the value of the attribute, only that if srsName key exists, then its general x,y coordinates.

So proper checks would be to check for the attribute, and if present, swap the coordinates.

**Comment by emmanuelmathot** [comment]
so, to understand correctly, this is an invalid gml because the poslist should be "lon lat lon lat ..." ?

``` xml
<gml:MultiSurface gml:id="1740061" srsName="EPSG:4326">
              <gml:surfaceMembers>
                <gml:Polygon gml:id="1740062">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>31.93 -117.79 31.74 -118.86 34.97 -119.67 35.36 -119.77 35.55 -118.66 35.16 -118.56 31.93 -117.79</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMembers>
            </gml:MultiSurface>
```

**Comment by s093294** [comment]
Thats how I read the GDAL stuff. GeoJson also uses long,lat for the default EPSG:4326 projection as reference.

I can update the PR to include a check for srsName attribute before swapping if needed.

**Comment by emmanuelmathot** [comment]
That seems a good solution.
So to sum up and in relation to the gdal document you presented:

- if srsName is specified
  * if srsName > 4000 and srsName < 5000
      + coordinates become lat long, following EPSG axis order (Y X)
- else
     + coordinates are processed lon lat following the default easting northing reference (X Y)
- if srsName is null or empty
     * coordinates are processed lon lat following the default easting northing reference (X Y)

It would be important that when srsName like 'EPSG:4326" is specified, it consider it like "urn:ogc:def:crs:EPSG::4326" as per gdal gdal with the setting GML_CONSIDER_EPSG_AS_URN to YES.

is that ok?

**Comment by s093294** [comment]
your check if srsName > 4000 and srsName < 5000 is not relevant. it should just be if srsName is presented, then its x,y order ( x=long,y=lat).

Unless you want to add support to parse srsName and look up the right order.

This is also a valid srsName for epsg 4326 ect, "urn:ogc:def:crs:OGC:1.3:CRS84".

My suggestion is:
if srsName is present, then the first coordinate is x and the second is y. And for the EPSG:4326 case this implies that long is x and lat is y.

Do it make sense?

**Comment by emmanuelmathot** [comment]
I am confused.
It would be the other way around to work closer to gdal. if srsName present, then the y is the first and x the second.
On my side, I need to recognise the EPSG:4326 coordinate reference system that uses the y x order.

**Pull request closed without merging**
