### PR TITLE
Update to .NET 4.6.1 and fix unit tests relative source paths

### PR DESCRIPTION
**Pull request by Siliconrob**
Update nuget references to latests stable versions i.e. NetwonSoft 9.x
and NetTopology

### CODE REVIEW

**Comment by Siliconrob** [comment]
On another note I would like to convert the project to .NET Core.  Would you prefer side by side projects if that was to be done i.e. All the same project names, but with .Core appended to them?

**Comment by Siliconrob** [comment]
Added appveyor build because your jenkins build was gone.

**Comment by Siliconrob** [comment]
Anything?

**Comment by emmanuelmathot** [comment]
Hello. Thank you for this valuable contribution. There is some delay in the merging because some of your changes (e.e.g implicit typing) do not meet our design patterns. In addition, we would like to have our software .net core compatible. This requires further tests.

**Comment by Siliconrob** [comment]
I can write further tests or change all the implicit typing back to explicit if that is what you want

**Comment by emmanuelmathot** [comment]
I integrated your changes but removed the implicit typing. I will still need further tests to release it.

**Comment by Siliconrob** [comment]
Thanks

I used the appveyor tool to run the tests included in the projects.  Said it passed all of them.  If you want me to write some specific tests I can do that.

**Pull request merged**
