### PR TITLE
static string FeatureExtensions.GeometryToWktString(IPosition position)

### PR DESCRIPTION
**Pull request by liaozhai**
Hi,
There's a little problem in the GeometryToWktString(IPosition position) method of the FeatureExtensions class. When the string.Format call is performed it doesn't take into account the possibility that a locale other than us-EN is used. As a result it produces an invalid WKT string, for example like this one:
POLYGON((37,891845703125 55,6279959542672,37,891845703125 55,9061151260116,37,3974609375 55,9061151260116,37,3974609375 55,6279959542672,37,891845703125 55,6279959542672))
To avoid this you need to supply CultureInfo.InvariantCulture parameter to the string.Format call.

### CODE REVIEW

**Comment by liaozhai** [comment]
By the way concatenating strings using + is a very bad idea. How about using the StringBuilder class?

**Comment by emmanuelmathot** [comment]
Thank you for reporting. I will check on that. If you have a solution combining StringBuilder class and CultureInfo.InvariantCulture, please pull request!

**Comment by liaozhai** [comment]
Thank you,

I have created a pull request that should remedy the issues. However I have used not StringBuilder, but string.Join which has a comparable performance under these circumtances. Unfortuately I have done so in the master branch. I'm new to GitHub. Nevertheless I hope this won't be a problem, since the code is rather straightforward.
The trouble with strings contatenation by means of the "+" operator arises from the nature of the .NET string type. Assignment creates a copy of the original string. 
See details  https://msdn.microsoft.com/en-us/library/ms228504.aspx


Пятница, 06 февраля 2015, 2:05 -08:00 от Emmanuel Mathot <notifications@github.com>:

**Comment by emmanuelmathot** [comment]
This is closed by PR #7.

**Pull request closed without merging**
